{% set name = "sentry-sdk" %}
{% set version = "1.44.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sentry-sdk-{{ version }}.tar.gz
  sha256: 24e6a53eeabffd2f95d952aa35ca52f0f4201d17f820ac9d3ff7244c665aaf68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - urllib3 >=1.25.7
    - certifi

test:
  requires:
    - pip
  imports:
    - sentry_sdk
  commands:
    - pip check

about:
  home: https://github.com/getsentry/sentry-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python SDK for Sentry.io
  description: |
    The official Python SDK for Sentry.io 
  doc_url: https://docs.sentry.io/platforms/python/
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - rxm7706
    - alippai
    - dgasmith
    - djsutherland
