{% set name = "sentry-sdk" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aa4314f877d9cd9add5a0c9ba18e3f27f99f7de835ce36bd150e48a41c7c646f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - urllib3 >=1.25.7
    - certifi

test:
  requires:
    - pip
  imports:
    - sentry_sdk
  commands:
    - pip check

about:
  home: https://github.com/getsentry/sentry-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python SDK for Sentry.io
  description: |
    The official Python SDK for Sentry.io 
  doc_url: https://docs.sentry.io/platforms/python/
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - rxm7706
    - alippai
    - dgasmith
    - djsutherland
