{% set name = "sentry-sdk" %}
{% set version = "1.40.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sentry-sdk-{{ version }}.tar.gz
  sha256: c98c8e9bb4dc8ff1e67473caf6467acfccf915dadcc26d0efb0d6791a8652610

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - urllib3 >=1.25.7
    - certifi

test:
  requires:
    - pip
  imports:
    - sentry_sdk
  commands:
    - pip check

about:
  home: https://github.com/getsentry/sentry-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python SDK for Sentry.io
  description: |
    The official Python SDK for Sentry.io 
  doc_url: https://docs.sentry.io/platforms/python/
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - rxm7706
    - alippai
    - dgasmith
    - djsutherland
