{% set name = "sentry-sdk" %}
{% set version = "2.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ee4a4d2ae8bfe3cac012dcf3e4607975904c137e1738116549fc3dbbb6ff0e36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - urllib3 >=1.25.7
    - certifi

test:
  requires:
    - pip
  imports:
    - sentry_sdk
  commands:
    - pip check

about:
  home: https://github.com/getsentry/sentry-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python SDK for Sentry.io
  description: |
    The official Python SDK for Sentry.io 
  doc_url: https://docs.sentry.io/platforms/python/
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - rxm7706
    - alippai
    - dgasmith
    - djsutherland
