{% set name = "sentry-sdk" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c5da96f77307d0afc7811f3adc736c363c52388700e449c6a5310be44c82376

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - urllib3 >=1.9
    - certifi

test:
  imports:
    - sentry_sdk

about:
  home: https://github.com/getsentry/sentry-python
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The new Python SDK for Sentry.io'
  description: |
    The new Python SDK for Sentry.io
  doc_url: https://docs.sentry.io/quickstart/?platform=python
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - dougalsutherland
